# Generated by Django 4.1.2 on 2022-11-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('numb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default=0, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(default='', max_length=255)),
                ('birt_date', models.DateField(null=True, verbose_name='Birth date')),
                ('work_experience', models.TextField(default='', max_length=255)),
                ('numb', models.IntegerField()),
                ('directions', models.ManyToManyField(to='MyAPI.directions')),
            ],
        ),
    ]
